// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProject = "tm_project"

// Project mapped from table <tm_project>
type Project struct {

	/*
		项目id

	*/
	PID int32 `gorm:"column:p_id;primaryKey;autoIncrement:true;comment:项目id" json:"p_id"`
	/*
		项目名称

	*/
	PName string `gorm:"column:p_name;not null;comment:项目名称" json:"p_name"`
	/*
		1:正常 2:禁用 3:完结

	*/
	PStatus int8 `gorm:"column:p_status;not null;default:1;comment:1:正常 2:禁用 3:完结" json:"p_status"`
	/*
		创建的用户id

	*/
	PCreateUserID int32 `gorm:"column:p_create_user_id;not null;comment:创建的用户id" json:"p_create_user_id"`
	/*
		创建人昵称

	*/
	PCreateUserName string `gorm:"column:p_create_user_name;not null;comment:创建人昵称" json:"p_create_user_name"`
	/*
		创建时间

	*/
	PCreateTime int32 `gorm:"column:p_create_time;not null;comment:创建时间" json:"p_create_time"`
	/*
		更改时间

	*/
	PUpdateTime int32 `gorm:"column:p_update_time;not null;comment:更改时间" json:"p_update_time"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}

// p_status 1:正常 2:禁用 3:完结
const PROJECT_STATUS_NORMAL = 1
const PROJECT_STATUS_BAN = 2
const PROJECT_STATUS_DONE = 3
