// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProjectUser = "tm_project_user"

// ProjectUser mapped from table <tm_project_user>
type ProjectUser struct {

	/*
		项目人员表id

	*/
	PuID int32 `gorm:"column:pu_id;primaryKey;autoIncrement:true;comment:项目人员表id" json:"pu_id"`
	/*
		项目id

	*/
	PuProjectID int32 `gorm:"column:pu_project_id;not null;comment:项目id" json:"pu_project_id"`
	/*
		用户id

	*/
	PuUserID int32 `gorm:"column:pu_user_id;not null;comment:用户id" json:"pu_user_id"`
	/*
		创建时间

	*/
	PuCreateTime int32 `gorm:"column:pu_create_time;not null;comment:创建时间" json:"pu_create_time"`
}

// TableName ProjectUser's table name
func (*ProjectUser) TableName() string {
	return TableNameProjectUser
}
