// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskComment = "tm_task_comment"

// TaskComment mapped from table <tm_task_comment>
type TaskComment struct {

	/*
		评论id

	*/
	TcID int32 `gorm:"column:tc_id;primaryKey;autoIncrement:true;comment:评论id" json:"tc_id"`
	/*
		任务id

	*/
	TcTaskID int32 `gorm:"column:tc_task_id;not null;comment:任务id" json:"tc_task_id"`
	/*
		评论人id

	*/
	TcUserID int32 `gorm:"column:tc_user_id;not null;comment:评论人id" json:"tc_user_id"`
	/*
		昵称

	*/
	TcNickName string `gorm:"column:tc_nick_name;not null;comment:昵称" json:"tc_nick_name"`
	/*
		头像地址

	*/
	TcAvatar string `gorm:"column:tc_avatar;not null;comment:头像地址" json:"tc_avatar"`
	/*
		评论内容

	*/
	TcComment string `gorm:"column:tc_comment;not null;comment:评论内容" json:"tc_comment"`
	/*
		绝对路径包含文件名

	*/
	TcAbsolutePath string `gorm:"column:tc_absolute_path;not null;comment:绝对路径包含文件名" json:"tc_absolute_path"`
	/*
		文件名

	*/
	TcFileName string `gorm:"column:tc_file_name;not null;comment:文件名" json:"tc_file_name"`
	/*
		创建时间

	*/
	TcCreateTime int32 `gorm:"column:tc_create_time;not null;comment:创建时间" json:"tc_create_time"`
}

// TableName TaskComment's table name
func (*TaskComment) TableName() string {
	return TableNameTaskComment
}
