// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTask = "tm_task"

// Task mapped from table <tm_task>
type Task struct {

	/*
		任务id

	*/
	TID int32 `gorm:"column:t_id;primaryKey;autoIncrement:true;comment:任务id" json:"t_id"`
	/*
		任务名称

	*/
	TName string `gorm:"column:t_name;not null;comment:任务名称" json:"t_name"`
	/*
		描述

	*/
	TDescribe string `gorm:"column:t_describe;not null;comment:描述" json:"t_describe"`
	/*
		排序数字

	*/
	TSort int32 `gorm:"column:t_sort;not null;comment:排序数字" json:"t_sort"`
	/*
		项目id

	*/
	TProjectID int32 `gorm:"column:t_project_id;not null;comment:项目id" json:"t_project_id"`
	/*
		任务标签id

	*/
	TTaskTagID int32 `gorm:"column:t_task_tag_id;not null;comment:任务标签id" json:"t_task_tag_id"`
	/*
		负责人id

	*/
	TBelongUserID int32 `gorm:"column:t_belong_user_id;not null;comment:负责人id" json:"t_belong_user_id"`
	/*
		负责人昵称

	*/
	TBelongUserName string `gorm:"column:t_belong_user_name;not null;comment:负责人昵称" json:"t_belong_user_name"`
	/*
		创建的用户id

	*/
	TCreateUserID int32 `gorm:"column:t_create_user_id;not null;comment:创建的用户id" json:"t_create_user_id"`
	/*
		创建人昵称

	*/
	TCreateUserName string `gorm:"column:t_create_user_name;not null;comment:创建人昵称" json:"t_create_user_name"`
	/*
		1:未完成 2:完成

	*/
	TStatus int8 `gorm:"column:t_status;not null;default:1;comment:1:未完成 2:完成" json:"t_status"`
	/*
		创建时间

	*/
	TCreateTime int32 `gorm:"column:t_create_time;not null;comment:创建时间" json:"t_create_time"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
